/**
 * 3D hand animations generated by `scripts/landmarks/extract_dynamic.py` from the CICESE
 * "Mexican Sign Language Alphabet (dynamic signs only)" dataset, frontal + 45° profile views
 * (Zenodo 10.5281/zenodo.14689869, CC BY 4.0). Each one is a real execution: the most
 * representative of ~100 executions by 20 people.
 */

import dynamic from '@/assets/signs/anim/dynamic.json';

/** 21 MediaPipe landmarks, each [x, y, z] in meters: x right, y down, z away from the viewer. */
export type HandFrame = number[][];

export type SignAnimation = {
  fps: number;
  /** Landmark whose path is drawn as a trail (the fingertip that "writes" the sign), if any. */
  trail: number | null;
  /** Whether the movement's depth was reconstructed from the 45° view. */
  depth: 'side' | 'none';
  /** +1/-1: turns (index_mcp − wrist) × (pinky_mcp − wrist) into the palm normal. */
  palmar: 1 | -1;
  source: { front: string; side: string | null };
  frames: HandFrame[];
};

export const ANIMATION_CREDIT = 'Animación basada en MSL Alphabet (CICESE, Zenodo) · CC BY 4.0';

const ANIMATIONS = dynamic as unknown as Record<string, SignAnimation>;

export function getSignAnimation(id: string): SignAnimation | undefined {
  return ANIMATIONS[id];
}
